version: '3.7'

services:
  web:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/portfolio
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
